name: test config change2

feign:
  hystrix:
    enabled: true
spring:
  cloud:
    stream: 
      instance-count: 1 
      instance-index: 0 
      bindings:
        stream-input:
          destination: stream-topic
          group: stream
          consumer: 
            partitioned: true
            delayed-exchange: true
        stream-output:
          destination: stream-topic
          group: stream
          producer:
            partition-key-expression: 1 
            partition-count: 2 
            delayed-exchange: true
  # 开启链路追踪
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1 # 配置采样比例，默认为 0.1
  # zipkin 地址
  zipkin:
    base-url: http://111.231.255.138:9411
    # 开启 zipkin
    enabled: true
    # 追踪消息的发送类型
    #sender:
      #type: rabbit
      
  rabbitmq:
    host: 111.231.255.138
    port: 5672
    username: rabbit
    password: rabbit
    
turbine:
  app-config: tool
  cluster-name-expression: new String("default")
  combine-host-port: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
